SHELL := /bin/bash

init: clean ## Import dependencies and prepare for the build
image: init docker-build ## Build the production Docker image
docker: docker-build docker-tag docker-push ## Build and push the production Docker image

clean: ## Delete the files generated by colcon build
	rm -rf build/
	rm -rf install/
	rm -rf log/

build: ## Build all the packages in Release mode (with debug symbols)
	colcon build  --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo

build-debug: ## Build all the packages in full Debug mode
	colcon build  --cmake-args -DCMAKE_BUILD_TYPE=Debug

build-package-sym: ## Build a specific package with symlink-install option and then source the environment. Must build the package without symlink flag before using this.  Append PACKAGE=package_name.
	colcon build --packages-select $(PACKAGE) --symlink-install
	source install/setup.bash

docker-build: ## Build the production Docker image.
	docker build --network=host --rm -t $(PERCEPTION_IMAGE) .

lint: ## Format all files
	pre-commit run --all-files

lint-file: ## Format a single file. Append FILE=path_to_file
	pre-commit run --verbose --files $(FILE)

test: ## Run all the tests for all the packages
	colcon test --ctest-args \
	--event-handlers console_cohesion+ console_stderr+ status+ summary+ \
	--return-code-on-test-failure

rviz:
	ros2 run rviz2 rviz2 -d config/default.rviz

#################################################################################
# Self Documenting Commands                                                     #
#################################################################################
# Inspired by <http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html>

.DEFAULT_GOAL := help

.PHONY: help build buildd

help:  ## Show this help.
	@recipe_max_length=`grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	awk '{print length($$1)}' | sort -nr | head -1`; \
	grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	sort | awk -v recipe_max_length=$$recipe_max_length 'BEGIN {FS = ":.*?## "}; \
	{printf "\033[36m%-" recipe_max_length "s\033[0m %s\n", $$1, $$2}'
